"""
Emit the geometry config for the C++ engine as plain key-value text.

config.yaml is the single source of truth, but C++ has no yaml parser and
these values can't all be recovered from the TensorRT engines — a (200, 200)
BEV grid says nothing about the metres it covers. Writing them here keeps the
C++ side free of duplicated constants that go stale when config.yaml changes.

infer.cpp cross-checks the shape entries against the engines' actual I/O and
errors on mismatch, which catches engines left over from a different
resolution.

Usage: python scripts/dump_grid_config.py
"""
import sys
import yaml
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "data" / "grid_config.txt"

LSS_DOWNSAMPLE = 16   # fixed by LiftSplatShoot in src/camera/lss.py
N_CAMS = 6
CAM_C = 64            # LiftSplatShoot.camC


def main():
    with open(ROOT / "config.yaml") as f:
        cfg = yaml.safe_load(f)

    cam = cfg['camera']
    img_h, img_w = cam['image_size']
    d_lo, d_hi, d_step = cam['dbound']

    if img_h % LSS_DOWNSAMPLE or img_w % LSS_DOWNSAMPLE:
        sys.exit(f"image_size {img_h}x{img_w} must divide by {LSS_DOWNSAMPLE}")

    lines = [
        "# Generated by scripts/dump_grid_config.py — do not edit by hand.",
        "# Mirrors camera.* in config.yaml.",
        f"n_cams {N_CAMS}",
        f"cam_c {CAM_C}",
        f"img_h {img_h}",
        f"img_w {img_w}",
        f"feat_h {img_h // LSS_DOWNSAMPLE}",
        f"feat_w {img_w // LSS_DOWNSAMPLE}",
        f"depth_bins {int((d_hi - d_lo) / d_step)}",
        f"dbound_start {d_lo}",
        f"dbound_step {d_step}",
    ]
    for axis in ("x", "y", "z"):
        lo, hi, step = cam[f"{axis}bound"]
        lines += [f"{axis}_min {lo}", f"{axis}_max {hi}", f"{axis}_step {step}"]

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
